CREATE TABLE IF NOT EXISTS `mydb`.`RENTAL_LOCATION` (
  `RENTAL_LOCATION_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL,
  `ADDRESS1` VARCHAR(100) NULL,
  `ADDRESS2` VARCHAR(100) NULL,
  `CITY` VARCHAR(45) NULL,
  `STATE` VARCHAR(45) NULL,
  `POSTAL_CODE` VARCHAR(45) NULL,
  PRIMARY KEY (`RENTAL_LOCATION_ID`),
  UNIQUE INDEX `RENTAL_LOCATION_ID_UNIQUE` (`RENTAL_LOCATION_ID` ASC));

CREATE TABLE IF NOT EXISTS `mydb`.`MEDIA` (
  `MEDIA_ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(100) NULL,
  `FORMAT` VARCHAR(45) NULL,
  `LENGTH` INT NULL,
  `RATING` INT NULL,
  `RENTAL_LOCATION_ID` INT NULL,
  `IS_AVAILABLE` TINYINT NULL,
  PRIMARY KEY (`MEDIA_ID`),
  INDEX `RENTAL_LOCATION_FK_idx` (`RENTAL_LOCATION_ID` ASC),
  CONSTRAINT `RENTAL_LOCATION_FK`
    FOREIGN KEY (`RENTAL_LOCATION_ID`)
    REFERENCES `mydb`.`RENTAL_LOCATION` (`RENTAL_LOCATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS `mydb`.`RENTAL` (
  `RENTAL_ID` INT NOT NULL AUTO_INCREMENT,
  `MEDIA_ID` INT NULL,
  `PICKUP_LOCATION_ID` INT NULL,
  `RETURN_LOCATION_ID` INT NULL,
  `PICKUP_DATE` DATE NULL,
  `RETURN_DATE` DATE NULL,
  `CUSTOMER_NAME` VARCHAR(100) NULL,
  PRIMARY KEY (`RENTAL_ID`),
  UNIQUE INDEX `RENTAL_ID_UNIQUE` (`RENTAL_ID` ASC),
  INDEX `RENTAL_LOCATION_FK2_idx` (`PICKUP_LOCATION_ID` ASC),
  INDEX `RENTAL_LOCATION_FK3_idx` (`RETURN_LOCATION_ID` ASC),
  INDEX `MEDIA_FK_idx` (`MEDIA_ID` ASC),
  CONSTRAINT `RENTAL_LOCATION_FK2`
    FOREIGN KEY (`PICKUP_LOCATION_ID`)
    REFERENCES `mydb`.`RENTAL_LOCATION` (`RENTAL_LOCATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RENTAL_LOCATION_FK3`
    FOREIGN KEY (`RETURN_LOCATION_ID`)
    REFERENCES `mydb`.`RENTAL_LOCATION` (`RENTAL_LOCATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MEDIA_FK`
    FOREIGN KEY (`MEDIA_ID`)
    REFERENCES `mydb`.`MEDIA` (`MEDIA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
/*
-- Query: SELECT * FROM mydb.rental_location
LIMIT 0, 1000

-- Date: 2019-12-01 15:13
*/
INSERT INTO `mydb`.`RENTAL_LOCATION` (`RENTAL_LOCATION_ID`,`NAME`,`ADDRESS1`,`ADDRESS2`,`CITY`,`STATE`,`POSTAL_CODE`) VALUES (1,'Gas Station','Address1','Address2','City','TX','PostalCode');
INSERT INTO `mydb`.`RENTAL_LOCATION` (`RENTAL_LOCATION_ID`,`NAME`,`ADDRESS1`,`ADDRESS2`,`CITY`,`STATE`,`POSTAL_CODE`) VALUES (2,'Grocery Store','3306 Trisle Pike',NULL,'Pivotal Springs','WA','15550-433');
INSERT INTO `mydb`.`RENTAL_LOCATION` (`RENTAL_LOCATION_ID`,`NAME`,`ADDRESS1`,`ADDRESS2`,`CITY`,`STATE`,`POSTAL_CODE`) VALUES (3,'Grocery Store2','3306 Trisle Pike',NULL,'Pivotal Springs','WA','15550-433');
INSERT INTO `mydb`.`RENTAL_LOCATION` (`RENTAL_LOCATION_ID`,`NAME`,`ADDRESS1`,`ADDRESS2`,`CITY`,`STATE`,`POSTAL_CODE`) VALUES (4,'Gas Station','Address1','Address2','City','State','PostalCode');

/*
-- Query: SELECT * FROM mydb.media
LIMIT 0, 1000

-- Date: 2019-12-01 15:09
*/
INSERT INTO `mydb`.`MEDIA` (`MEDIA_ID`,`TITLE`,`FORMAT`,`LENGTH`,`RATING`,`RENTAL_LOCATION_ID`,`IS_AVAILABLE`) VALUES (1,'peli','mp4',90,2,1,1);
    
    